apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web-container
        image: tariq126/my-custom-app:1.0
        ports:
        - containerPort: 80
